spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/alibaba_guangmingding/configTest.git
          username: byj1575116@163.com
          password: byj15751160802
          basedir: /var/config/sell
    bus:
      id: ${spring.application.name}:${spring.cloud.config.profile}:${random.value}
  rabbitmq:
    host: 192.168.43.91
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  # 将eureka的容器id变为真是ip地址
  instance:
    prefer-ip-address: true
#bus-refreshc
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
server:
  port: 8088